-- CLP Learning Hub - complete schema
-- Generated by concatenating supabase/migrations/*.sql in order.
-- Paste this whole file into the SQL editor of a fresh Supabase project.
-- Every migration is idempotent, so re-running is safe.


-- ============================================================
-- 000_base_schema.sql
-- ============================================================

-- CLP Learning Hub - base schema.
--
-- Reconstructed from the application code, because the original schema.sql
-- referenced by SETUP.md was never committed to the repo.
-- Run this FIRST on a new Supabase project, then 001, 002, 003 in order.
-- Idempotent - safe to re-run.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------------
create table if not exists patients (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete cascade,
  email text,
  name text,
  role text not null default 'patient',
  access_type text not null default 'single_course',
  created_at timestamptz not null default now()
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'patients_role_check') then
    alter table patients add constraint patients_role_check
      check (role in ('admin', 'patient', 'instructor'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'patients_access_type_check') then
    alter table patients add constraint patients_access_type_check
      check (access_type in ('single_course', 'all_access'));
  end if;
end $$;

-- Helper functions. plpgsql (never inlined) + SECURITY DEFINER so that policies
-- on `patients` can call them without re-entering their own RLS check. A plain
-- `language sql` function here would be inlined and cause infinite recursion.
create or replace function public.current_patient_id() returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select id into result from patients where auth_user_id = auth.uid() limit 1;
  return result;
end $$;

create or replace function public.current_user_role() returns text
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return result;
end $$;

create or replace function public.is_staff() returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return coalesce(result in ('admin', 'instructor'), false);
end $$;

create or replace function public.is_admin() returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return coalesce(result = 'admin', false);
end $$;

-- Every new auth user gets a patients row.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.patients (auth_user_id, email, name, role, access_type)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'patient',
    'single_course'
  )
  on conflict (auth_user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------
create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  category text,
  thumbnail_url text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists modules (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses (id) on delete cascade,
  title text not null,
  "order" integer not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists modules_course_idx on modules (course_id, "order");

-- The FK must be named lessons_module_id_fkey: the app relies on that name in
-- its PostgREST joins (lessons!lessons_module_id_fkey).
create table if not exists lessons (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references modules (id) on delete cascade,
  title text not null,
  slug text not null,
  "order" integer not null default 1,
  youtube_video_id text,
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists lessons_module_idx on lessons (module_id, "order");
create unique index if not exists lessons_module_slug_key on lessons (module_id, slug);

-- ---------------------------------------------------------------------------
-- Enrollment workflow
-- ---------------------------------------------------------------------------
create table if not exists enrollment_requests (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references patients (id) on delete cascade,
  course_id uuid not null references courses (id) on delete cascade,
  status text not null default 'requested'
    check (status in ('requested', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references patients (id) on delete set null
);
create index if not exists enrollment_requests_status_idx on enrollment_requests (status, requested_at desc);
create index if not exists enrollment_requests_patient_idx on enrollment_requests (patient_id);

create table if not exists enrollments (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references patients (id) on delete cascade,
  course_id uuid not null references courses (id) on delete cascade,
  status text not null default 'active'
    check (status in ('active', 'completed')),
  enrolled_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists enrollments_patient_idx on enrollments (patient_id, status);
create index if not exists enrollments_course_idx on enrollments (course_id, status);

-- onConflict "enrollment_id,lesson_id" in the progress API needs this index.
create table if not exists lesson_progress (
  id uuid primary key default gen_random_uuid(),
  enrollment_id uuid not null references enrollments (id) on delete cascade,
  lesson_id uuid not null references lessons (id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz
);
create unique index if not exists lesson_progress_enrollment_lesson_key
  on lesson_progress (enrollment_id, lesson_id);

create table if not exists certificates (
  id uuid primary key default gen_random_uuid(),
  enrollment_id uuid not null references enrollments (id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- Quizzes (lesson level) and assessments (module level)
-- ---------------------------------------------------------------------------
create table if not exists quizzes (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid references lessons (id) on delete cascade,
  module_id uuid references modules (id) on delete cascade,
  title text,
  created_at timestamptz not null default now()
);
create index if not exists quizzes_lesson_idx on quizzes (lesson_id);
create index if not exists quizzes_module_idx on quizzes (module_id);

create table if not exists quiz_questions (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null references quizzes (id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null
);
create index if not exists quiz_questions_quiz_idx on quiz_questions (quiz_id);

create table if not exists quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null references quizzes (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  score integer not null default 0,
  answers jsonb,
  attempted_at timestamptz not null default now()
);
create index if not exists quiz_attempts_patient_idx on quiz_attempts (patient_id, quiz_id);

create table if not exists assessments (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references modules (id) on delete cascade,
  title text not null,
  instructions text,
  pass_threshold integer not null default 70,
  created_at timestamptz not null default now()
);
create index if not exists assessments_module_idx on assessments (module_id);

create table if not exists assessment_questions (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references assessments (id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null,
  "order" integer not null default 1
);
create index if not exists assessment_questions_assessment_idx
  on assessment_questions (assessment_id, "order");

create table if not exists assessment_attempts (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references assessments (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  enrollment_id uuid references enrollments (id) on delete cascade,
  score integer not null default 0,
  passed boolean not null default false,
  answers jsonb,
  attempted_at timestamptz not null default now()
);
create index if not exists assessment_attempts_patient_idx
  on assessment_attempts (patient_id, assessment_id);

-- ---------------------------------------------------------------------------
-- Assignments
-- ---------------------------------------------------------------------------
create table if not exists assignments (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references lessons (id) on delete cascade,
  title text not null,
  prompt text,
  created_at timestamptz not null default now()
);
create index if not exists assignments_lesson_idx on assignments (lesson_id);

-- The FK must be named assignment_submissions_patient_id_fkey: the admin and
-- instructor grading queries join through that name.
create table if not exists assignment_submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references assignments (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  enrollment_id uuid references enrollments (id) on delete cascade,
  response text,
  status text not null default 'submitted'
    check (status in ('submitted', 'approved', 'needs_revision')),
  feedback text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references patients (id) on delete set null
);
create unique index if not exists assignment_submissions_patient_assignment_key
  on assignment_submissions (patient_id, assignment_id);
create index if not exists assignment_submissions_status_idx
  on assignment_submissions (status, submitted_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table patients               enable row level security;
alter table courses                enable row level security;
alter table modules                enable row level security;
alter table lessons                enable row level security;
alter table enrollment_requests    enable row level security;
alter table enrollments            enable row level security;
alter table lesson_progress        enable row level security;
alter table certificates           enable row level security;
alter table quizzes                enable row level security;
alter table quiz_questions         enable row level security;
alter table quiz_attempts          enable row level security;
alter table assessments            enable row level security;
alter table assessment_questions   enable row level security;
alter table assessment_attempts    enable row level security;
alter table assignments            enable row level security;
alter table assignment_submissions enable row level security;

-- patients ------------------------------------------------------------------
drop policy if exists "read own patient row" on patients;
create policy "read own patient row" on patients
  for select using (auth_user_id = auth.uid() or is_staff());

drop policy if exists "update own patient row" on patients;
create policy "update own patient row" on patients
  for update using (auth_user_id = auth.uid() or is_admin())
  with check (auth_user_id = auth.uid() or is_admin());

-- courses -------------------------------------------------------------------
drop policy if exists "read published courses" on courses;
create policy "read published courses" on courses
  for select using (published or is_staff());

drop policy if exists "admins write courses" on courses;
create policy "admins write courses" on courses
  for all using (is_admin()) with check (is_admin());

-- modules / lessons ---------------------------------------------------------
drop policy if exists "read modules of visible courses" on modules;
create policy "read modules of visible courses" on modules
  for select using (
    is_staff() or exists (
      select 1 from courses c
      where c.id = modules.course_id
        and (c.published or exists (
          select 1 from enrollments e
          where e.course_id = c.id and e.patient_id = current_patient_id()
        ))
    )
  );

drop policy if exists "admins write modules" on modules;
create policy "admins write modules" on modules
  for all using (is_admin()) with check (is_admin());

drop policy if exists "read lessons of visible courses" on lessons;
create policy "read lessons of visible courses" on lessons
  for select using (
    is_staff() or exists (
      select 1 from modules m
      join courses c on c.id = m.course_id
      where m.id = lessons.module_id
        and (c.published or exists (
          select 1 from enrollments e
          where e.course_id = c.id and e.patient_id = current_patient_id()
        ))
    )
  );

drop policy if exists "admins write lessons" on lessons;
create policy "admins write lessons" on lessons
  for all using (is_admin()) with check (is_admin());

-- enrollment workflow -------------------------------------------------------
drop policy if exists "read own requests" on enrollment_requests;
create policy "read own requests" on enrollment_requests
  for select using (patient_id = current_patient_id() or is_staff());

drop policy if exists "create own requests" on enrollment_requests;
create policy "create own requests" on enrollment_requests
  for insert with check (patient_id = current_patient_id());

drop policy if exists "admins review requests" on enrollment_requests;
create policy "admins review requests" on enrollment_requests
  for update using (is_admin()) with check (is_admin());

drop policy if exists "read own enrollments" on enrollments;
create policy "read own enrollments" on enrollments
  for select using (patient_id = current_patient_id() or is_staff());

drop policy if exists "admins create enrollments" on enrollments;
create policy "admins create enrollments" on enrollments
  for insert with check (is_admin());

-- Learners complete their own enrollment; admins may correct any.
drop policy if exists "update own enrollment" on enrollments;
create policy "update own enrollment" on enrollments
  for update using (patient_id = current_patient_id() or is_admin())
  with check (patient_id = current_patient_id() or is_admin());

drop policy if exists "own lesson progress" on lesson_progress;
create policy "own lesson progress" on lesson_progress
  for all using (
    exists (
      select 1 from enrollments e
      where e.id = lesson_progress.enrollment_id
        and (e.patient_id = current_patient_id() or is_staff())
    )
  ) with check (
    exists (
      select 1 from enrollments e
      where e.id = lesson_progress.enrollment_id
        and e.patient_id = current_patient_id()
    )
  );

-- certificates: the patient read policy is added in 001; issuing uses the
-- service role, which bypasses RLS.
drop policy if exists "staff read certificates" on certificates;
create policy "staff read certificates" on certificates
  for select using (is_staff());

-- quizzes and assessments ---------------------------------------------------
drop policy if exists "read quizzes when entitled" on quizzes;
create policy "read quizzes when entitled" on quizzes
  for select using (is_staff() or current_patient_id() is not null);

drop policy if exists "admins write quizzes" on quizzes;
create policy "admins write quizzes" on quizzes
  for all using (is_admin()) with check (is_admin());

drop policy if exists "read quiz questions when entitled" on quiz_questions;
create policy "read quiz questions when entitled" on quiz_questions
  for select using (is_staff() or current_patient_id() is not null);

drop policy if exists "admins write quiz questions" on quiz_questions;
create policy "admins write quiz questions" on quiz_questions
  for all using (is_admin()) with check (is_admin());

drop policy if exists "own quiz attempts" on quiz_attempts;
create policy "own quiz attempts" on quiz_attempts
  for all using (patient_id = current_patient_id() or is_staff())
  with check (patient_id = current_patient_id());

drop policy if exists "read assessments when entitled" on assessments;
create policy "read assessments when entitled" on assessments
  for select using (is_staff() or current_patient_id() is not null);

drop policy if exists "admins write assessments" on assessments;
create policy "admins write assessments" on assessments
  for all using (is_admin()) with check (is_admin());

drop policy if exists "read assessment questions when entitled" on assessment_questions;
create policy "read assessment questions when entitled" on assessment_questions
  for select using (is_staff() or current_patient_id() is not null);

drop policy if exists "admins write assessment questions" on assessment_questions;
create policy "admins write assessment questions" on assessment_questions
  for all using (is_admin()) with check (is_admin());

drop policy if exists "own assessment attempts" on assessment_attempts;
create policy "own assessment attempts" on assessment_attempts
  for all using (patient_id = current_patient_id() or is_staff())
  with check (patient_id = current_patient_id());

-- assignments ---------------------------------------------------------------
drop policy if exists "read assignments when entitled" on assignments;
create policy "read assignments when entitled" on assignments
  for select using (is_staff() or current_patient_id() is not null);

drop policy if exists "admins write assignments" on assignments;
create policy "admins write assignments" on assignments
  for all using (is_admin()) with check (is_admin());

drop policy if exists "read own submissions" on assignment_submissions;
create policy "read own submissions" on assignment_submissions
  for select using (patient_id = current_patient_id() or is_staff());

drop policy if exists "write own submissions" on assignment_submissions;
create policy "write own submissions" on assignment_submissions
  for insert with check (patient_id = current_patient_id());

drop policy if exists "update submissions" on assignment_submissions;
create policy "update submissions" on assignment_submissions
  for update using (patient_id = current_patient_id() or is_staff())
  with check (patient_id = current_patient_id() or is_staff());

-- ============================================================
-- 001_certificates.sql
-- ============================================================

-- Certificates: numbering, issue date, and public verification support.
-- Idempotent — safe to re-run.

alter table certificates
  add column if not exists certificate_number text,
  add column if not exists issued_at timestamptz not null default now();

-- Backfill any rows created before numbering existed.
update certificates
set certificate_number = 'CLP-' || to_char(coalesce(issued_at, now()), 'YYYY') || '-' ||
                         upper(substr(replace(id::text, '-', ''), 1, 8))
where certificate_number is null;

alter table certificates alter column certificate_number set not null;

create unique index if not exists certificates_number_key
  on certificates (certificate_number);

-- One certificate per enrollment.
create unique index if not exists certificates_enrollment_key
  on certificates (enrollment_id);

-- Patients may read their own certificates.
alter table certificates enable row level security;

drop policy if exists "patients read own certificates" on certificates;
create policy "patients read own certificates" on certificates
  for select using (
    enrollment_id in (
      select e.id from enrollments e
      join patients p on p.id = e.patient_id
      where p.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- 002_instructor_role.sql
-- ============================================================

-- Instructor role: a third role alongside admin and patient.
-- Instructors author and manage only the courses assigned to them.
-- Idempotent — safe to re-run.

-- 1. Allow 'instructor' as a role value.
--    Handles `role` being a text/varchar column with a CHECK constraint (the common case).
--    If your `role` column is a Postgres ENUM instead, this block raises a notice and you
--    must run this ONE line on its own, outside any transaction, before re-running:
--        alter type <your_enum_name> add value 'instructor';
--    (ALTER TYPE ... ADD VALUE cannot legally run inside a DO block.)
do $$
declare
  kind char;
  enum_name text;
begin
  select t.typtype, t.typname
    into kind, enum_name
  from pg_attribute a
  join pg_type t on t.oid = a.atttypid
  where a.attrelid = 'patients'::regclass
    and a.attname = 'role'
    and a.attnum > 0;

  if kind = 'e' then
    if exists (
      select 1 from pg_enum e
      join pg_type t on t.oid = e.enumtypid
      where t.typname = enum_name and e.enumlabel = 'instructor'
    ) then
      raise notice 'role enum % already has instructor', enum_name;
    else
      raise exception
        'role is enum %. Run this alone first: alter type % add value ''instructor'';',
        enum_name, enum_name;
    end if;
  else
    if exists (
      select 1 from pg_constraint
      where conrelid = 'patients'::regclass and conname = 'patients_role_check'
    ) then
      alter table patients drop constraint patients_role_check;
    end if;
    alter table patients add constraint patients_role_check
      check (role in ('admin', 'patient', 'instructor'));
  end if;
end $$;

-- 2. Course ownership. Null instructor_id = clinic-owned, admin-managed (all existing courses).
alter table courses
  add column if not exists instructor_id uuid references patients (id) on delete set null;

create index if not exists courses_instructor_id_idx on courses (instructor_id);

-- 3. Instructor profile fields, shown on course pages later.
alter table patients
  add column if not exists bio text,
  add column if not exists title text;

-- 4. RLS: instructors may read the patients rows of learners enrolled in their courses.
--    Named distinctly so it cannot collide with existing policies.
alter table patients enable row level security;

drop policy if exists "instructors read own course learners" on patients;
-- Must NOT select from `patients` here: a policy on `patients` that queries
-- `patients` re-enters its own RLS check and recurses. current_patient_id() is
-- a plpgsql SECURITY DEFINER function, so it resolves without that.
create policy "instructors read own course learners" on patients
  for select using (
    exists (
      select 1
      from enrollments e
      join courses c on c.id = e.course_id
      where e.patient_id = patients.id
        and c.instructor_id = current_patient_id()
    )
  );

-- ============================================================
-- 003_reviews_discussions.sql
-- ============================================================

-- Course reviews and lesson discussions.
-- Idempotent — safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. Course reviews
-- ---------------------------------------------------------------------------
create table if not exists course_reviews (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  body text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One review per person per course; re-reviewing edits the existing row.
create unique index if not exists course_reviews_course_patient_key
  on course_reviews (course_id, patient_id);
create index if not exists course_reviews_course_idx
  on course_reviews (course_id, created_at desc);

-- Denormalised aggregates so the catalog can sort and display without a join.
alter table courses
  add column if not exists avg_rating numeric(3,2) not null default 0,
  add column if not exists review_count integer not null default 0;

create or replace function refresh_course_rating() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  target uuid := coalesce(new.course_id, old.course_id);
begin
  update courses c
  set avg_rating = coalesce((select round(avg(r.rating)::numeric, 2) from course_reviews r where r.course_id = target), 0),
      review_count = (select count(*) from course_reviews r where r.course_id = target)
  where c.id = target;
  return null;
end $$;

drop trigger if exists course_reviews_aggregate on course_reviews;
create trigger course_reviews_aggregate
  after insert or update or delete on course_reviews
  for each row execute function refresh_course_rating();

-- Backfill for any rows that predate the trigger.
update courses c
set avg_rating = coalesce((select round(avg(r.rating)::numeric, 2) from course_reviews r where r.course_id = c.id), 0),
    review_count = (select count(*) from course_reviews r where r.course_id = c.id);

alter table course_reviews enable row level security;

-- Reviews are public: anyone browsing the catalog can read them.
drop policy if exists "anyone reads reviews" on course_reviews;
create policy "anyone reads reviews" on course_reviews
  for select using (true);

-- Writes go through the API, which checks enrollment. This policy is the backstop.
drop policy if exists "patients write own reviews" on course_reviews;
create policy "patients write own reviews" on course_reviews
  for all using (
    patient_id in (select id from patients where auth_user_id = auth.uid())
  ) with check (
    patient_id in (select id from patients where auth_user_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 2. Lesson discussions
-- ---------------------------------------------------------------------------
create table if not exists lesson_comments (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references lessons (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  parent_id uuid references lesson_comments (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists lesson_comments_lesson_idx
  on lesson_comments (lesson_id, created_at);
create index if not exists lesson_comments_parent_idx
  on lesson_comments (parent_id);

alter table lesson_comments enable row level security;

-- Readable by people enrolled in the course the lesson belongs to, plus staff.
drop policy if exists "enrolled read lesson comments" on lesson_comments;
create policy "enrolled read lesson comments" on lesson_comments
  for select using (
    exists (
      select 1
      from lessons l
      join modules m on m.id = l.module_id
      join enrollments e on e.course_id = m.course_id
      join patients p on p.id = e.patient_id
      where l.id = lesson_comments.lesson_id
        and p.auth_user_id = auth.uid()
    )
    or exists (
      select 1 from patients me
      where me.auth_user_id = auth.uid()
        and me.role in ('admin', 'instructor')
    )
  );

drop policy if exists "authors write own comments" on lesson_comments;
create policy "authors write own comments" on lesson_comments
  for all using (
    patient_id in (select id from patients where auth_user_id = auth.uid())
  ) with check (
    patient_id in (select id from patients where auth_user_id = auth.uid())
  );

-- ============================================================
-- 004_fix_rls_recursion.sql
-- ============================================================

-- Fixes "infinite recursion detected in policy for relation patients".
--
-- The helpers in 000 were `language sql`. Postgres inlines plain SQL functions
-- into the calling query, which drops the SECURITY DEFINER context - so a
-- policy on `patients` that called is_staff() ended up querying `patients`
-- again and re-entering its own policy.
--
-- plpgsql functions are never inlined, so the definer context survives and the
-- lookup bypasses RLS as intended.
-- Idempotent - safe to re-run.

create or replace function public.current_patient_id() returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select id into result from patients where auth_user_id = auth.uid() limit 1;
  return result;
end $$;

create or replace function public.current_user_role() returns text
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return result;
end $$;

create or replace function public.is_staff() returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return coalesce(result in ('admin', 'instructor'), false);
end $$;

create or replace function public.is_admin() returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  result text;
begin
  select role into result from patients where auth_user_id = auth.uid() limit 1;
  return coalesce(result = 'admin', false);
end $$;

-- ============================================================
-- 005_fix_instructor_patient_policy.sql
-- ============================================================

-- Fixes the actual cause of "infinite recursion detected in policy for
-- relation patients".
--
-- 002 added this policy on `patients`:
--
--   ... join patients me on me.id = c.instructor_id
--       where me.auth_user_id = auth.uid()
--
-- A policy on `patients` that itself selects from `patients` re-enters its own
-- RLS check, so any read of the table recursed. current_patient_id() is a
-- plpgsql SECURITY DEFINER function, so calling it resolves the instructor
-- without touching `patients` inside the policy.
-- Idempotent - safe to re-run.

drop policy if exists "instructors read own course learners" on patients;
create policy "instructors read own course learners" on patients
  for select using (
    exists (
      select 1
      from enrollments e
      join courses c on c.id = e.course_id
      where e.patient_id = patients.id
        and c.instructor_id = current_patient_id()
    )
  );

-- ============================================================
-- 006_prevent_duplicate_enrollments.sql
-- ============================================================

-- Prevents a learner holding two active enrollments in the same course.
--
-- The lesson page resolves the enrollment with .single(), which throws when two
-- rows match, so a duplicate silently redirected the learner away from every
-- lesson in that course. Nothing stopped a second enrollment being created.
--
-- Idempotent - safe to re-run.

-- 1. Clean up existing duplicates.
--    Deliberately conservative: only ever deletes a row that has no progress,
--    no certificate, and is not the oldest of its group. A duplicate holding
--    any learner work is left alone for a human to reconcile.
with ranked as (
  select
    e.id,
    row_number() over (
      partition by e.patient_id, e.course_id
      order by e.enrolled_at
    ) as rn
  from enrollments e
  where e.status = 'active'
),
deletable as (
  select r.id
  from ranked r
  where r.rn > 1
    and not exists (select 1 from lesson_progress lp where lp.enrollment_id = r.id)
    and not exists (select 1 from certificates c where c.enrollment_id = r.id)
)
delete from enrollments where id in (select id from deletable);

-- 2. Stop it happening again. A partial index, so re-enrolling after finishing
--    a course still works - completed rows do not participate in the constraint.
create unique index if not exists enrollments_one_active_per_course
  on enrollments (patient_id, course_id)
  where status = 'active';

-- ============================================================
-- 007_instructor_authoring.sql
-- ============================================================

-- Lets instructors author the content of courses assigned to them.
--
-- 000 granted write access on course content to admins only, so the builder
-- components (which write straight to the tables through RLS) refused every
-- instructor edit. Each policy below scopes the instructor to their own
-- courses via courses.instructor_id; admins keep the blanket access from 000.
--
-- Idempotent - safe to re-run.

-- Does the signed-in instructor own this course?
create or replace function public.owns_course(target uuid) returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  owner uuid;
begin
  select instructor_id into owner from courses where id = target;
  return owner is not null and owner = current_patient_id();
end $$;

-- Resolve the owning course for a module / lesson / quiz, so the policies below
-- can be written against the course regardless of nesting depth.
create or replace function public.course_of_module(target uuid) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select course_id into result from modules where id = target;
  return result;
end $$;

create or replace function public.course_of_lesson(target uuid) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select m.course_id into result
  from lessons l join modules m on m.id = l.module_id
  where l.id = target;
  return result;
end $$;

create or replace function public.course_of_quiz(target uuid) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select coalesce(course_of_lesson(q.lesson_id), course_of_module(q.module_id))
    into result
  from quizzes q where q.id = target;
  return result;
end $$;

create or replace function public.course_of_assessment(target uuid) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  result uuid;
begin
  select course_of_module(a.module_id) into result from assessments a where a.id = target;
  return result;
end $$;

-- Courses: an instructor may edit their own, but not create or delete one.
-- Assignment stays an admin action, so instructors cannot grant themselves work.
drop policy if exists "instructors update own courses" on courses;
create policy "instructors update own courses" on courses
  for update using (owns_course(id)) with check (owns_course(id));

-- Modules
drop policy if exists "instructors write own modules" on modules;
create policy "instructors write own modules" on modules
  for all using (owns_course(course_id)) with check (owns_course(course_id));

-- Lessons
drop policy if exists "instructors write own lessons" on lessons;
create policy "instructors write own lessons" on lessons
  for all using (owns_course(course_of_module(module_id)))
  with check (owns_course(course_of_module(module_id)));

-- Quizzes and their questions
drop policy if exists "instructors write own quizzes" on quizzes;
create policy "instructors write own quizzes" on quizzes
  for all using (owns_course(coalesce(course_of_lesson(lesson_id), course_of_module(module_id))))
  with check (owns_course(coalesce(course_of_lesson(lesson_id), course_of_module(module_id))));

drop policy if exists "instructors write own quiz questions" on quiz_questions;
create policy "instructors write own quiz questions" on quiz_questions
  for all using (owns_course(course_of_quiz(quiz_id)))
  with check (owns_course(course_of_quiz(quiz_id)));

-- Assessments and their questions
drop policy if exists "instructors write own assessments" on assessments;
create policy "instructors write own assessments" on assessments
  for all using (owns_course(course_of_module(module_id)))
  with check (owns_course(course_of_module(module_id)));

drop policy if exists "instructors write own assessment questions" on assessment_questions;
create policy "instructors write own assessment questions" on assessment_questions
  for all using (owns_course(course_of_assessment(assessment_id)))
  with check (owns_course(course_of_assessment(assessment_id)));

-- Assignments
drop policy if exists "instructors write own assignments" on assignments;
create policy "instructors write own assignments" on assignments
  for all using (owns_course(course_of_lesson(lesson_id)))
  with check (owns_course(course_of_lesson(lesson_id)));

-- ============================================================
-- 008_instructor_course_creation.sql
-- ============================================================

-- Lets instructors create their own courses, and records who created each one.
--
-- created_by is deliberately separate from instructor_id: instructor_id is the
-- current owner and an admin may reassign it, while created_by is an immutable
-- record of authorship that admins can always see.
--
-- Idempotent - safe to re-run.

alter table courses
  add column if not exists created_by uuid references patients (id) on delete set null;

create index if not exists courses_created_by_idx on courses (created_by);

-- Existing courses: the assigned instructor is the best available author.
update courses set created_by = instructor_id
where created_by is null and instructor_id is not null;

-- An instructor may create a course only with themselves as owner and author,
-- so nobody can create work in someone else's name.
drop policy if exists "instructors create own courses" on courses;
create policy "instructors create own courses" on courses
  for insert with check (
    current_user_role() = 'instructor'
    and instructor_id = current_patient_id()
    and created_by = current_patient_id()
  );

-- Reassignment stays an admin action, but an instructor must not be able to
-- rewrite authorship on a course they own either. Enforced in the API; this
-- trigger is the backstop for direct table writes.
create or replace function public.protect_course_authorship() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if is_admin() then
    return new;
  end if;
  if new.created_by is distinct from old.created_by then
    raise exception 'created_by cannot be changed';
  end if;
  if new.instructor_id is distinct from old.instructor_id then
    raise exception 'instructor_id can only be changed by an admin';
  end if;
  return new;
end $$;

drop trigger if exists courses_protect_authorship on courses;
create trigger courses_protect_authorship
  before update on courses
  for each row execute function public.protect_course_authorship();

-- ============================================================
-- 009_certificate_template.sql
-- ============================================================

-- Makes the certificate design and wording editable by admins.
--
-- Everything on the certificate was hardcoded in the component, so changing the
-- organisation name, the wording, or adding a signature meant a code deploy.
-- A single-row table holds it instead.
--
-- Idempotent - safe to re-run.

create table if not exists certificate_template (
  -- Single row: the primary key can only ever be true.
  id boolean primary key default true check (id),

  organisation_name text not null default 'Clinic Living Plus',
  logo_initials text not null default 'CL',

  title text not null default 'Certificate of Completion',
  intro_line text not null default 'This certifies that',
  middle_line text not null default 'has successfully completed',
  footer_note text,

  signature_name text,
  signature_role text,

  accent_color text not null default '#2e7d32',

  show_category boolean not null default true,
  show_issued_date boolean not null default true,
  show_certificate_number boolean not null default true,
  show_signature boolean not null default false,

  updated_at timestamptz not null default now(),
  updated_by uuid references patients (id) on delete set null
);

-- Seed the single row.
insert into certificate_template (id) values (true) on conflict (id) do nothing;

alter table certificate_template enable row level security;

-- Readable by everyone: the public verification page renders a certificate
-- without a session.
drop policy if exists "anyone reads certificate template" on certificate_template;
create policy "anyone reads certificate template" on certificate_template
  for select using (true);

-- Only admins may change how certificates look. Instructors are deliberately
-- excluded: the template is clinic-wide, not per-course.
drop policy if exists "admins write certificate template" on certificate_template;
create policy "admins write certificate template" on certificate_template
  for all using (is_admin()) with check (is_admin());

-- ============================================================
-- 010_selected_course_access.sql
-- ============================================================

-- A third access tier: staff choose exactly which courses a learner gets.
--
-- single_course lets the learner pick any one course at a time; all_access lets
-- them take everything. Neither lets the clinic say "this person does these two
-- courses", which is what a care plan usually looks like.
--
-- Idempotent - safe to re-run.

-- 1. Allow the new tier.
do $$ begin
  if exists (select 1 from pg_constraint where conname = 'patients_access_type_check') then
    alter table patients drop constraint patients_access_type_check;
  end if;
  alter table patients add constraint patients_access_type_check
    check (access_type in ('single_course', 'all_access', 'selected_courses'));
end $$;

-- 2. Which courses a learner has been given, and by whom.
create table if not exists patient_course_access (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references patients (id) on delete cascade,
  course_id uuid not null references courses (id) on delete cascade,
  granted_by uuid references patients (id) on delete set null,
  granted_at timestamptz not null default now()
);

create unique index if not exists patient_course_access_unique
  on patient_course_access (patient_id, course_id);
create index if not exists patient_course_access_patient_idx
  on patient_course_access (patient_id);
create index if not exists patient_course_access_course_idx
  on patient_course_access (course_id);

alter table patient_course_access enable row level security;

-- Learners see what they have been given; staff see everything.
drop policy if exists "read course access" on patient_course_access;
create policy "read course access" on patient_course_access
  for select using (
    patient_id = current_patient_id() or is_staff()
  );

-- Admins assign any course.
drop policy if exists "admins assign courses" on patient_course_access;
create policy "admins assign courses" on patient_course_access
  for all using (is_admin()) with check (is_admin());

-- Instructors assign only their own courses, so one instructor cannot put a
-- learner into a colleague's course.
drop policy if exists "instructors assign own courses" on patient_course_access;
create policy "instructors assign own courses" on patient_course_access
  for all using (owns_course(course_id)) with check (owns_course(course_id));

-- ============================================================
-- 011_protect_lesson_content.sql
-- ============================================================

-- Stops lesson rows, and with them every YouTube video id, from being readable
-- by anyone who is not enrolled.
--
-- The policy written in 000 granted a full row read whenever the course was
-- published. Since the anon key is public by design, that meant an anonymous
-- visitor could query the lessons table directly and collect youtube_video_id
-- and notes for every published course - the app gated the lesson *page*, but
-- never the data behind it.
--
-- Curriculum previews on the public course page now come from a view that
-- exposes titles and ordering only, so the catalog still works.
--
-- Idempotent - safe to re-run.

-- 1. Lesson rows: enrolled learners and staff only.
drop policy if exists "read lessons of visible courses" on lessons;
drop policy if exists "read lessons when entitled" on lessons;
create policy "read lessons when entitled" on lessons
  for select using (
    is_staff()
    or exists (
      select 1
      from modules m
      join enrollments e on e.course_id = m.course_id
      where m.id = lessons.module_id
        and e.patient_id = current_patient_id()
    )
  );

-- 2. Public curriculum: titles and ordering, never the video id or notes.
create or replace view public_curriculum
with (security_invoker = off) as
select
  c.id           as course_id,
  c.slug         as course_slug,
  m.id           as module_id,
  m.title        as module_title,
  m."order"      as module_order,
  l.id           as lesson_id,
  l.title        as lesson_title,
  l."order"      as lesson_order
from courses c
join modules m on m.course_id = c.id
left join lessons l on l.module_id = m.id
where c.published;

grant select on public_curriculum to anon, authenticated;

-- ============================================================
-- 012_drive_video.sql
-- ============================================================

-- Lets a lesson hold a Google Drive file instead of a YouTube video.
--
-- Both columns coexist on purpose: existing lessons keep working on YouTube
-- while new ones can be moved to Drive one at a time. The player prefers the
-- Drive file when both are set.
--
-- Nothing here is public. The id is only ever read by the server, which checks
-- the enrollment before it fetches anything from Drive, and the lesson row is
-- already restricted to enrolled learners and staff by migration 011.
--
-- Idempotent - safe to re-run.

alter table lessons add column if not exists drive_file_id text;

comment on column lessons.drive_file_id is
  'Google Drive file id. Served through /api/lessons/[lessonId]/video, never linked directly.';

-- ============================================================
-- 013_role_grants.sql
-- ============================================================

-- Grants the Supabase roles access to the public schema.
--
-- 000 created every table but never granted anything, so on a freshly created
-- project PostgREST answers `42501 permission denied` for even the service
-- role. The original project had these grants from however it was first built;
-- recreating the project from these migrations alone did not.
--
-- This is the standard Supabase posture: the roles hold table privileges and
-- row level security decides what any given caller may actually see. Every
-- table in this schema has RLS enabled (see 000, 002, 003, 009, 010), so
-- granting here does not widen access - without it, nothing works at all.
--
-- Idempotent - safe to re-run.

grant usage on schema public to anon, authenticated, service_role;

grant all on all tables    in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all functions in schema public to anon, authenticated, service_role;

-- Anything created later inherits the same grants, so a new table added in a
-- future migration does not silently become unreadable.
alter default privileges in schema public
  grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public
  grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema public
  grant all on functions to anon, authenticated, service_role;

-- ============================================================
-- 014_question_types.sql
-- ============================================================

-- Lets a question be something other than "pick one of four".
--
-- Both question tables previously assumed a single correct option, with
-- correct_answer holding that option's text. That still holds for
-- multiple_choice. The new types reuse the same column:
--
--   multiple_choice  correct_answer is the correct option's text
--   checkboxes       correct_answer is a JSON array of the correct options
--   short_answer     correct_answer is the expected text, compared
--                    case-insensitively and trimmed; options stays empty
--
-- Existing rows become multiple_choice, which is what they already were.
--
-- Idempotent - safe to re-run.

alter table quiz_questions
  add column if not exists question_type text not null default 'multiple_choice';

alter table assessment_questions
  add column if not exists question_type text not null default 'multiple_choice';

-- Dropped and recreated so re-running does not fail on an existing constraint.
alter table quiz_questions drop constraint if exists quiz_questions_type_check;
alter table quiz_questions add constraint quiz_questions_type_check
  check (question_type in ('multiple_choice', 'checkboxes', 'short_answer'));

alter table assessment_questions drop constraint if exists assessment_questions_type_check;
alter table assessment_questions add constraint assessment_questions_type_check
  check (question_type in ('multiple_choice', 'checkboxes', 'short_answer'));

-- ============================================================
-- 015_assignment_files.sql
-- ============================================================

-- Lets a learner attach a file to an assignment submission, alongside the
-- existing text response.
--
-- Files live in a private Storage bucket, never a public one. Path shape is
-- {auth_user_id}/{assignment_id}/{filename}, so storage's own RLS can key off
-- the first path segment without a join back to patients - the same pattern
-- Postgres RLS uses via current_patient_id(), just expressed for storage.
--
-- Idempotent - safe to re-run.

alter table assignment_submissions add column if not exists file_path text;
alter table assignment_submissions add column if not exists file_name text;
alter table assignment_submissions add column if not exists file_size integer;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'assignment-files',
  'assignment-files',
  false,
  20971520, -- 20 MB
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "assignment files: owner can manage" on storage.objects;
create policy "assignment files: owner can manage" on storage.objects
  for all using (
    bucket_id = 'assignment-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'assignment-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "assignment files: staff can read" on storage.objects;
create policy "assignment files: staff can read" on storage.objects
  for select using (
    bucket_id = 'assignment-files'
    and is_staff()
  );

-- ============================================================
-- 016_staff_training.sql
-- ============================================================

-- Internal staff training: how the team uses its own tools (PTD, Calendly,
-- Canva, client workflows). Deliberately separate from courses/modules/
-- lessons rather than reusing them with a flag - training has no enrollment,
-- no certificate, no quiz, and must never be reachable by a learner. Keeping
-- it a distinct set of tables means the existing patient-facing RLS on
-- courses/lessons is never in the path, so there is nothing to accidentally
-- expose to a learner as this evolves.
--
-- Every table here is staff-only, gated by the same is_staff() helper the
-- rest of the schema already uses.
--
-- Idempotent - safe to re-run.

create table if not exists training_modules (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  "order" integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists training_lessons (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references training_modules (id) on delete cascade,
  title text not null,
  "order" integer not null default 1,
  drive_file_id text,
  notes text,
  created_at timestamptz not null default now()
);

-- Who has watched what. Optional in the UI, but useful once there is more
-- than a couple of staff and someone wants to know who has completed
-- onboarding.
create table if not exists training_progress (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references training_lessons (id) on delete cascade,
  patient_id uuid not null references patients (id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (lesson_id, patient_id)
);

alter table training_modules enable row level security;
alter table training_lessons enable row level security;
alter table training_progress enable row level security;

drop policy if exists "training modules: staff only" on training_modules;
create policy "training modules: staff only" on training_modules
  for all using (is_staff()) with check (is_staff());

drop policy if exists "training lessons: staff only" on training_lessons;
create policy "training lessons: staff only" on training_lessons
  for all using (is_staff()) with check (is_staff());

-- Each staff member manages their own completion record; any staff member can
-- see the whole list, which is what makes an admin's completion overview
-- possible.
drop policy if exists "training progress: staff can read all" on training_progress;
create policy "training progress: staff can read all" on training_progress
  for select using (is_staff());

drop policy if exists "training progress: mark own completion" on training_progress;
create policy "training progress: mark own completion" on training_progress
  for insert with check (is_staff() and patient_id = current_patient_id());

drop policy if exists "training progress: clear own completion" on training_progress;
create policy "training progress: clear own completion" on training_progress
  for delete using (is_staff() and patient_id = current_patient_id());
